
package net.mahtabalam.ws.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CountryImpl", targetNamespace = "http://ws.mahtabalam.net/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CountryImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.mahtabalam.net/CountryImpl/getDistrictsRequest", output = "http://ws.mahtabalam.net/CountryImpl/getDistrictsResponse")
    public int getDistricts(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0Www
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.mahtabalam.net/CountryImpl/getCapitalRequest", output = "http://ws.mahtabalam.net/CountryImpl/getCapitalResponse")
    public String getCapital(
        @WebParam(name = "arg0www", partName = "arg0www")
        String arg0Www);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.mahtabalam.net/CountryImpl/getAirportsRequest", output = "http://ws.mahtabalam.net/CountryImpl/getAirportsResponse")
    public String getAirports(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.mahtabalam.net/CountryImpl/getPlacesToVisitRequest", output = "http://ws.mahtabalam.net/CountryImpl/getPlacesToVisitResponse")
    public String getPlacesToVisit(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.mahtabalam.net/CountryImpl/getInterestingFactsRequest", output = "http://ws.mahtabalam.net/CountryImpl/getInterestingFactsResponse")
    public String getInterestingFacts(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.mahtabalam.net/CountryImpl/getLanguagesRequest", output = "http://ws.mahtabalam.net/CountryImpl/getLanguagesResponse")
    public String getLanguages(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
